// Package migrationutil
// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package migrationutil

import (
	"time"

	gorm "gorm.io/gorm"
)

var _ = time.Time{}

// MigrationSchema Migration
var MigrationSchema Migration

// NewMigration new schema
func NewMigration() *Migration {
	return &Migration{}
}

// Migration CHARSET utf8mb4
// Migration 数据库迁移
// 文档地址：https://gorm.io/docs/models.html
// MySQL 支持 unsigned
// Postgres 不支持 unsigned
// MySQL 支持 auto_increment
// Postgres : serial or bigserial
type Migration struct {
	Id                  uint64    `gorm:"column:id;type:uint;autoIncrement;comment:ID" json:"id"`
	ServerVersion       string    `gorm:"column:server_version;type:string;size:255;not null;default:'';comment:服务版本" json:"server_version"`
	MigrationIdentifier string    `gorm:"column:migration_identifier;unique;type:string;size:255;not null;default:'';comment:迁移key：唯一" json:"migration_identifier"`
	MigrationBatch      uint      `gorm:"column:migration_batch;type:uint;not null;default:0;comment:迁移批次" json:"migration_batch"`
	MigrationDesc       string    `gorm:"column:migration_desc;type:text;not null;comment:迁移描述" json:"migration_desc"`
	MigrationExtraInfo  string    `gorm:"column:migration_extra_info;type:json;not null;comment:迁移：额外信息" json:"migration_extra_info"`
	CreatedTime         time.Time `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
	UpdatedTime         time.Time `gorm:"column:updated_time;type:time;not null;comment:更新时间" json:"updated_time"`
}

// TableName table name
func (s *Migration) TableName() string {
	return DefaultMigrationTableName
}

// CreateTableMigrator create table migrator
func (s *Migration) CreateTableMigrator(migrator gorm.Migrator) MigrationRepo {
	return NewCreateTable(migrator, s)
}

// DropTableMigrator create table migrator
func (s *Migration) DropTableMigrator(migrator gorm.Migrator) MigrationRepo {
	return NewDropTable(migrator, s)
}
