// Package migrationutil
// Package repos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package migrationutil

import (
	gormutil "github.com/ikaiguang/go-srv-kit/data/gorm"
)

// MigrationDataRepo repo
type MigrationDataRepo interface {
	Create(dataModel *MigrationEntity) error
	ExistCreate(dataModel *MigrationEntity) (anotherModel *MigrationEntity, isNotFound bool, err error)
	CreateInBatches(dataModels []*MigrationEntity, batchSize int) error
	Insert(dataModels []*MigrationEntity) error
	Update(dataModel *MigrationEntity) error
	ExistUpdate(dataModel *MigrationEntity) (anotherModel *MigrationEntity, isNotFound bool, err error)
	QueryOneById(id interface{}) (dataModel *MigrationEntity, isNotFound bool, err error)
	QueryOneByIdentifier(identifier string) (dataModel *MigrationEntity, isNotFound bool, err error)
	QueryOneByConditions(conditions map[string]interface{}) (dataModel *MigrationEntity, isNotFound bool, err error)
	QueryAllByConditions(conditions map[string]interface{}) (dataModels []*MigrationEntity, err error)
	List(conditions map[string]interface{}, paginatorArgs *gormutil.PaginatorArgs) (dataModels []*MigrationEntity, totalNumber int64, err error)
	Delete(dataModel *MigrationEntity) error
	DeleteByIds(ids interface{}) error
}
