// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: testdata/ping-service/api/ping-service/v1/services/ping.service.v1.proto

package servicev1

import (
	context "context"
	resources "github.com/ikaiguang/go-srv-kit/testdata/ping-service/api/ping-service/v1/resources"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SrvPing_Ping_FullMethodName = "/kit.api.ping.servicev1.SrvPing/Ping"
)

// SrvPingClient is the client API for SrvPing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SrvPing ping服务
type SrvPingClient interface {
	// Ping ping
	//
	// 测试PingV1
	Ping(ctx context.Context, in *resources.PingReq, opts ...grpc.CallOption) (*resources.PingResp, error)
}

type srvPingClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvPingClient(cc grpc.ClientConnInterface) SrvPingClient {
	return &srvPingClient{cc}
}

func (c *srvPingClient) Ping(ctx context.Context, in *resources.PingReq, opts ...grpc.CallOption) (*resources.PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(resources.PingResp)
	err := c.cc.Invoke(ctx, SrvPing_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvPingServer is the server API for SrvPing service.
// All implementations must embed UnimplementedSrvPingServer
// for forward compatibility.
//
// SrvPing ping服务
type SrvPingServer interface {
	// Ping ping
	//
	// 测试PingV1
	Ping(context.Context, *resources.PingReq) (*resources.PingResp, error)
	mustEmbedUnimplementedSrvPingServer()
}

// UnimplementedSrvPingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSrvPingServer struct{}

func (UnimplementedSrvPingServer) Ping(context.Context, *resources.PingReq) (*resources.PingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSrvPingServer) mustEmbedUnimplementedSrvPingServer() {}
func (UnimplementedSrvPingServer) testEmbeddedByValue()                 {}

// UnsafeSrvPingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvPingServer will
// result in compilation errors.
type UnsafeSrvPingServer interface {
	mustEmbedUnimplementedSrvPingServer()
}

func RegisterSrvPingServer(s grpc.ServiceRegistrar, srv SrvPingServer) {
	// If the following call pancis, it indicates UnimplementedSrvPingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SrvPing_ServiceDesc, srv)
}

func _SrvPing_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvPingServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrvPing_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvPingServer).Ping(ctx, req.(*resources.PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvPing_ServiceDesc is the grpc.ServiceDesc for SrvPing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvPing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kit.api.ping.servicev1.SrvPing",
	HandlerType: (*SrvPingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SrvPing_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testdata/ping-service/api/ping-service/v1/services/ping.service.v1.proto",
}
