// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.6
// source: testdata/ping-service/api/ping-service/v1/enums/ping.enum.v1.proto

package enumv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingInit PingInit enum
type PingInitEnum_PingInit int32

const (
	// UNSPECIFIED 未指定
	PingInitEnum_UNSPECIFIED PingInitEnum_PingInit = 0
)

// Enum value maps for PingInitEnum_PingInit.
var (
	PingInitEnum_PingInit_name = map[int32]string{
		0: "UNSPECIFIED",
	}
	PingInitEnum_PingInit_value = map[string]int32{
		"UNSPECIFIED": 0,
	}
)

func (x PingInitEnum_PingInit) Enum() *PingInitEnum_PingInit {
	p := new(PingInitEnum_PingInit)
	*p = x
	return p
}

func (x PingInitEnum_PingInit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PingInitEnum_PingInit) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_enumTypes[0].Descriptor()
}

func (PingInitEnum_PingInit) Type() protoreflect.EnumType {
	return &file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_enumTypes[0]
}

func (x PingInitEnum_PingInit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PingInitEnum_PingInit.Descriptor instead.
func (PingInitEnum_PingInit) EnumDescriptor() ([]byte, []int) {
	return file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDescGZIP(), []int{0, 0}
}

// PingInitEnum PingInitEnum enum
type PingInitEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingInitEnum) Reset() {
	*x = PingInitEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingInitEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingInitEnum) ProtoMessage() {}

func (x *PingInitEnum) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingInitEnum.ProtoReflect.Descriptor instead.
func (*PingInitEnum) Descriptor() ([]byte, []int) {
	return file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDescGZIP(), []int{0}
}

var File_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto protoreflect.FileDescriptor

var file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDesc = []byte{
	0x0a, 0x42, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x69, 0x6e, 0x67,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x75, 0x6d,
	0x73, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6b, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x69,
	0x6e, 0x67, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x76, 0x31, 0x22, 0x2b, 0x0a, 0x0c, 0x50, 0x69, 0x6e,
	0x67, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x1b, 0x0a, 0x08, 0x50, 0x69, 0x6e,
	0x67, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x42, 0x81, 0x01, 0x0a, 0x13, 0x6b, 0x69, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x69, 0x6e, 0x67, 0x2c, 0x65, 0x6e, 0x75, 0x6d, 0x76, 0x31, 0x42, 0x10,
	0x4b, 0x69, 0x74, 0x41, 0x70, 0x69, 0x50, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x31,
	0x50, 0x01, 0x5a, 0x56, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x6b, 0x61, 0x69, 0x67, 0x75, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x72, 0x76, 0x2d,
	0x6b, 0x69, 0x74, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x69, 0x6e,
	0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x69,
	0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x73, 0x3b, 0x65, 0x6e, 0x75, 0x6d, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDescOnce sync.Once
	file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDescData = file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDesc
)

func file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDescGZIP() []byte {
	file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDescOnce.Do(func() {
		file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDescData)
	})
	return file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDescData
}

var file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_goTypes = []any{
	(PingInitEnum_PingInit)(0), // 0: kit.api.ping.enumv1.PingInitEnum.PingInit
	(*PingInitEnum)(nil),       // 1: kit.api.ping.enumv1.PingInitEnum
}
var file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_init() }
func file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_init() {
	if File_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PingInitEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_goTypes,
		DependencyIndexes: file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_depIdxs,
		EnumInfos:         file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_enumTypes,
		MessageInfos:      file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_msgTypes,
	}.Build()
	File_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto = out.File
	file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_rawDesc = nil
	file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_goTypes = nil
	file_testdata_ping_service_api_ping_service_v1_enums_ping_enum_v1_proto_depIdxs = nil
}
