syntax = "proto3";

package kit.etcdpkg;

option go_package           = "github.com/ikaiguang/go-consul-kit/etcd;etcdpkg";
option java_multiple_files  = true;
option java_package         = "kit.etcdpkg";
option java_outer_classname = "KitEtcdPkg";

import "google/protobuf/duration.proto";

// Config etcd config
message Config {
  repeated string endpoints             = 1;
  string username                       = 2;
  string password                       = 3;
  google.protobuf.Duration dial_timeout = 4;  // (s)
  bytes ca_cert                         = 5;
  bool insecure_skip_verify             = 6;
}
