// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package testdataerrorv1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknown(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ERROR_UNKNOWN.String() && e.Code == 404
}

func ErrorUnknown(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ERROR_UNKNOWN.String(), fmt.Sprintf(format, args...))
}
