// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.6
// source: testdata/ping-service/api/testdata-service/v1/resources/testdata.resource.v1.proto

package resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TestReq 请求
type TestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 请求消息
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TestReq) Reset() {
	*x = TestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestReq) ProtoMessage() {}

func (x *TestReq) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestReq.ProtoReflect.Descriptor instead.
func (*TestReq) Descriptor() ([]byte, []int) {
	return file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDescGZIP(), []int{0}
}

func (x *TestReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TestResp 响应
type TestResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason   string            `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message  string            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data     *TestRespData     `protobuf:"bytes,100,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TestResp) Reset() {
	*x = TestResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResp) ProtoMessage() {}

func (x *TestResp) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResp.ProtoReflect.Descriptor instead.
func (*TestResp) Descriptor() ([]byte, []int) {
	return file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDescGZIP(), []int{1}
}

func (x *TestResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TestResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TestResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestResp) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TestResp) GetData() *TestRespData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TestRespData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TestRespData) Reset() {
	*x = TestRespData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRespData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRespData) ProtoMessage() {}

func (x *TestRespData) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRespData.ProtoReflect.Descriptor instead.
func (*TestRespData) Descriptor() ([]byte, []int) {
	return file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDescGZIP(), []int{2}
}

func (x *TestRespData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto protoreflect.FileDescriptor

var file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDesc = []byte{
	0x0a, 0x52, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x64, 0x61, 0x74, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x6b, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x76,
	0x31, 0x22, 0x23, 0x0a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x9d, 0x02, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4f, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6b, 0x69,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6b, 0x69, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x28, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x9d, 0x01, 0x0a, 0x1b, 0x6b, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x76, 0x31,
	0x42, 0x18, 0x4b, 0x69, 0x74, 0x41, 0x70, 0x69, 0x54, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x62, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6b, 0x61, 0x69, 0x67, 0x75, 0x61,
	0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x72, 0x76, 0x2d, 0x6b, 0x69, 0x74, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x3b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDescOnce sync.Once
	file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDescData = file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDesc
)

func file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDescGZIP() []byte {
	file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDescOnce.Do(func() {
		file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDescData)
	})
	return file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDescData
}

var file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_goTypes = []any{
	(*TestReq)(nil),      // 0: kit.api.testdata.resourcev1.TestReq
	(*TestResp)(nil),     // 1: kit.api.testdata.resourcev1.TestResp
	(*TestRespData)(nil), // 2: kit.api.testdata.resourcev1.TestRespData
	nil,                  // 3: kit.api.testdata.resourcev1.TestResp.MetadataEntry
}
var file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_depIdxs = []int32{
	3, // 0: kit.api.testdata.resourcev1.TestResp.metadata:type_name -> kit.api.testdata.resourcev1.TestResp.MetadataEntry
	2, // 1: kit.api.testdata.resourcev1.TestResp.data:type_name -> kit.api.testdata.resourcev1.TestRespData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_init()
}
func file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_init() {
	if File_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TestResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TestRespData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_goTypes,
		DependencyIndexes: file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_depIdxs,
		MessageInfos:      file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_msgTypes,
	}.Build()
	File_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto = out.File
	file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_rawDesc = nil
	file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_goTypes = nil
	file_testdata_ping_service_api_testdata_service_v1_resources_testdata_resource_v1_proto_depIdxs = nil
}
