syntax = "proto3";

package kit.mongopkg;

option go_package           = "github.com/ikaiguang/go-srv-kit/data/mongo/v3;mongo";
option java_multiple_files  = true;
option java_package         = "kit.mongopkg";
option java_outer_classname = "KitMongoPkg";

import "google/protobuf/duration.proto";

// Config mongo config
message Config {
  bool enable                                 = 100;
  bool debug                                  = 1;
  string app_name                             = 2;
  repeated string hosts                       = 3;
  string addr                                 = 4;
  string database                             = 5;
  uint32 max_pool_size                        = 6;
  uint32 min_pool_size                        = 7;
  uint32 max_connecting                       = 8;
  google.protobuf.Duration connect_timeout    = 9;
  google.protobuf.Duration timeout            = 10;
  google.protobuf.Duration heartbeat_interval = 11;
  google.protobuf.Duration max_conn_idle_time = 12;
  google.protobuf.Duration slow_threshold     = 13;
}
