# app 程序
app:
  name: srv_kit
  version: 1.0.0
  # env 开发环境；值：DEVELOP、TESTING、PREVIEW、PRODUCTION
  env: develop
  endpoints:
    - https://uufff.com
  metadata:
    id: "${app.name}_${app.version}_${app.env}"

# server 服务
server:
  http:
    network:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    network:
    addr: 0.0.0.0:9000
    timeout: 1s

# log 日志
log:
  console:
    enable: true
    # level 日志级别；值：DEBUG、INFO、WARN、ERROR、FATAL
    level: debug
  file:
    enable: true
    # level 日志级别；值：DEBUG、INFO、WARN、ERROR、FATAL
    level: DEBUG
    dir: ./
    filename: logs
    # rotate_time 轮询规则：n久 或 文件大小rotate_size(默认：52428800 # 50<<20 = 50M)
    rotate_time: 0s
    # rotate_size 轮询规则：按文件大小rotate_size(默认：52428800 # 50<<20 = 50M)
    rotate_size: 52428800
    # storage_counter 存储：n个 或 有效期storage_age(默认：2592000s = 30天)
    storage_counter: 0
    # storage_age 存储n久(默认：2592000s = 30天)
    storage_age: 2592000s

# data 数据
data:
  database:
    driver: mysql
    source: root:Mysql.123456@tcp(127.0.0.1:3306)/muses_user?parseTime=True
    table_prefix: ms_
    slow_threshold: 0.2s
    logger_level: 4 # 1:Silent,2:Error,3:Warn,4:Info
    logger_colorful: true
  redis:
    network:
    addr: 127.0.0.1:6379
    password:
    db: 0
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s


