# app 程序
app:
  name: go-srv-kit
  version: v1.0.0
  # env 开发环境；值：DEVELOP、TESTING、PREVIEW、PRODUCTION
  env: develop
  # env_branch 环境分支；main、feature/xxx、fix/xxx
  env_branch: main
  # endpoints 自定义的endpoint
  endpoints:
    - https://uufff.com
  metadata:
    id: "${app.name}_${app.env}_${app.env_branch}_${app.version}"
