# app 程序
app:
  name: go-srv-kit
  version: v1.0.0
  # env 开发环境；值：DEVELOP、TESTING、PREVIEW、PRODUCTION
  env: develop
  endpoints:
    - https://uufff.com
  metadata:
    id: "${app.name}_${app.version}_${app.env}"
  # auth 验证
  auth:
    default_key: 2MJRyKnANhtezTrD
    service_key: 6EZ5y7YBdv3KqAP0
    admin_key: IqD6bQvJodkLUa92
    api_key: WgxqFMe4VGBJU1Th
    web_key: QhqJvKm8cCXgLzaE
    app_key: WH5GNvPDlsIn3SEM
    h5_key: Z2tjUumyS8cbgdzJ
  # setting 设置
  setting:
    enable_migrate_db: true
    enable_schedule_task: false
