# app 程序
app:
  name: go-srv-kit
  version: v1.0.0
  # env 开发环境；值：DEVELOP、TESTING、PREVIEW、PRODUCTION
  env: develop
  # env_branch 环境分支；main、feature/xxx、fix/xxx
  env_branch: main
  # endpoints 自定义的endpoint
  endpoints:
    - https://uufff.com
  metadata:
    id: "${app.name}_${app.env}_${app.env_branch}_${app.version}"
  # auth 验证
  auth:
    default_key: 2MJRyKnANhtezTrD
    service_key: 6EZ5y7YBdv3KqAP0
    admin_key: IqD6bQvJodkLUa92
    api_key: WgxqFMe4VGBJU1Th
    web_key: QhqJvKm8cCXgLzaE
    app_key: WH5GNvPDlsIn3SEM
    h5_key: Z2tjUumyS8cbgdzJ
    manager_key: re5CDJcnhEB1lpzY
  # setting 设置
  setting:
    # enable_service_registry 服务注册
    enable_service_registry: false
    # enable_migrate_db 数据库迁移
    enable_migrate_db: true
    # enable_schedule_task 定时任务
    enable_schedule_task: false
