# app 程序
app:
  name: go-srv-kit
  version: v1.0.0
  # env 开发环境；值：DEVELOP、TESTING、PREVIEW、PRODUCTION
  env: develop
  endpoints:
    - https://uufff.com
  metadata:
    id: "${app.name}_${app.version}_${app.env}"
  # auth 验证
  auth:
    admin_key: nN8H6ySVpqwfKUITG7zaF5xuCEvhtbgJ
    api_key: POHU9qtjTL4h3yRZIB05DxzKnSgowVfF
    web_key: Qsar09wIJjKfD7RSybzOPpFould15TvX
    service_key: hJnS58CbF4NXKD6WIdBOqlfPUpyizVoe
  # setting 设置
  setting:
    enable_migrate_db: true
    enable_schedule_task: false
