package errorutil

import (
	stdhttp "net/http"
)

var _ = stdhttp.StatusOK

var (
	ERROR_UNKNOWN               = "未知错误"
	ERROR_REQUEST_FAILED        = "请求失败"
	ERROR_RECORD_NOT_FOUND      = "请求的内容未找到或已删除"
	ERROR_RECORD_ALREADY_EXISTS = "数据已存在"
	ERROR_NETWORK_ERROR         = "网络开小差了，请稍后再试"
	ERROR_NETWORK_TIMEOUT       = "请求超时"
	ERROR_CONNECTION            = "链接错误"
	ERROR_UNIMPLEMENTED         = "未实现"
	ERROR_FATAL                 = "服务内部错误"
	ERROR_PANIC                 = "服务内部错误"
	ERROR_REQUEST_NOT_SUPPORT   = "暂不支持此次请求"
	ERROR_DB                    = "数据错误"
	ERROR_REDIS                 = "redis缓存错误"
	ERROR_RABBIT_MQ             = "rabbitMQ消息队列错误"
	ERROR_RABBIT_KAFKA          = "kafka消息队列错误"
	ERROR_MONGO                 = "mongo数据库错误"

	ERROR_CONTINUE            = "请继续请求"
	ERROR_SWITCHING_PROTOCOLS = "请切换协议"
	ERROR_PROCESSING          = "将继续执行请求"

	ERROR_OK                     = "请求成功"
	ERROR_CREATED                = "请求已被接受，等待资源响应"
	ERROR_ACCEPTED               = "请求已被接受，但尚未处理"
	ERROR_NON_AUTHORITATIVE_INFO = "请求已成功处理，结果来自第三方拷贝"
	ERROR_NO_CONTENT             = "请求已成功处理，但无返回内容"
	ERROR_RESET_CONTENT          = "请求已成功处理，但需重置内容"
	ERROR_PARTIAL_CONTENT        = "请求已成功处理，但仅返回了部分内容"
	ERROR_MULTI_STATUS           = "请求已成功处理，返回了多个状态的XML消息"
	ERROR_ALREADY_REPORTED       = "响应已发送"
	ERROR_I_M_USED               = "已完成响应"

	ERROR_MULTIPLE_CHOICES   = "返回多条重定向供选择"
	ERROR_MOVED_PERMANENTLY  = "永久重定向"
	ERROR_FOUND              = "临时重定向"
	ERROR_SEE_OTHER          = "当前请求的资源在其它地址"
	ERROR_NOT_MODIFIED       = "请求资源与本地缓存相同，未修改"
	ERROR_USE_PROXY          = "必须通过代理访问"
	ERROR_EMPTY306           = "请切换代理" // Switch Proxy
	ERROR_TEMPORARY_REDIRECT = "临时重定向"
	ERROR_PERMANENT_REDIRECT = "永久重定向，且禁止改变http方法"

	ERROR_BAD_REQUEST                     = "请求错误或参数错误"
	ERROR_UNAUTHORIZED                    = "请先进行身份认证"
	ERROR_PAYMENT_REQUIRED                = "code=402"
	ERROR_FORBIDDEN                       = "无权限访问"
	ERROR_NOT_FOUND                       = "请求的内容未找到或已删除"
	ERROR_METHOD_NOT_ALLOWED              = "不允许的请求方法"
	ERROR_NOT_ACCEPTABLE                  = "无法响应，因资源无法满足客户端条件"
	ERROR_PROXY_AUTH_REQUIRED             = "请通过代理的身份认证"
	ERROR_REQUEST_TIMEOUT                 = "请求超时"
	ERROR_CONFLICT                        = "请求存在冲突"
	ERROR_GONE                            = "资源已被删除"
	ERROR_LENGTH_REQUIRED                 = "无法处理该请求"
	ERROR_PRECONDITION_FAILED             = "请求条件错误"
	ERROR_REQUEST_ENTITY_TOO_LARGE        = "请求的实体过大"
	ERROR_REQUEST_URI_TOO_LONG            = "请求的URI过长"
	ERROR_UNSUPPORTED_MEDIA_TYPE          = "无法处理的媒体格式"
	ERROR_REQUESTED_RANGE_NOT_SATISFIABLE = "请求范围不符合要求"
	ERROR_EXPECTATION_FAILED              = "请求未满足期望值"
	ERROR_TEAPOT                          = "TEAPOT"
	ERROR_MISDIRECTED_REQUEST             = "错误的请求"
	ERROR_UNPROCESSABLE_ENTITY            = "请求的语义错误"
	ERROR_LOCKED                          = "当前资源被锁定"
	ERROR_FAILED_DEPENDENCY               = "当前请求失败"
	ERROR_TOO_EARLY                       = "未知的请求"
	ERROR_UPGRADE_REQUIRED                = "请切换或升级请求协议"
	ERROR_PRECONDITION_REQUIRED           = "请求未带条件"
	ERROR_TOO_MANY_REQUESTS               = "请求过于频繁，请稍后再试"
	ERROR_REQUEST_HEADER_FIELDS_TOO_LARGE = "请求头过大"
	ERROR_UNAVAILABLE_FOR_LEGAL_REASONS   = "访问被拒绝(法律的要求)"

	ERROR_INTERNAL_SERVER                 = "网络开小差了，请稍后再试"
	ERROR_NOT_IMPLEMENTED                 = "服务器不支持的请求方法"
	ERROR_BAD_GATEWAY                     = "网关无响应"
	ERROR_SERVICE_UNAVAILABLE             = "服务器端临时错误"
	ERROR_GATEWAY_TIMEOUT                 = "网关超时"
	ERROR_HTTP_VERSION_NOT_SUPPORTED      = "服务器不支持的HTTP版本"
	ERROR_VARIANT_ALSO_NEGOTIATES         = "服务器内部配置错误"
	ERROR_INSUFFICIENT_STORAGE            = "服务器无法存储请求"
	ERROR_LOOP_DETECTED                   = "服务器因死循环而终止操作"
	ERROR_NOT_EXTENDED                    = "获取资源策略未被满足"
	ERROR_NETWORK_AUTHENTICATION_REQUIRED = "请携带许可凭证进行访问"
)
