// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/auth/v1/auth.v1.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserStatus 枚举值
type UserStatusEnum_UserStatus int32

const (
	// UNSPECIFIED 未指定
	UserStatusEnum_UNSPECIFIED UserStatusEnum_UserStatus = 0
	// INITIAL 初始状态
	UserStatusEnum_INITIAL UserStatusEnum_UserStatus = 1
	// ENABLE 启用
	UserStatusEnum_ENABLE UserStatusEnum_UserStatus = 2
	// DISABLE 禁用
	UserStatusEnum_DISABLE UserStatusEnum_UserStatus = 3
	// WHITELIST 白名单
	UserStatusEnum_WHITELIST UserStatusEnum_UserStatus = 4
	// BLACKLIST 黑名单
	UserStatusEnum_BLACKLIST UserStatusEnum_UserStatus = 5
	// DELETED 已删除
	UserStatusEnum_DELETED UserStatusEnum_UserStatus = 6
)

// Enum value maps for UserStatusEnum_UserStatus.
var (
	UserStatusEnum_UserStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INITIAL",
		2: "ENABLE",
		3: "DISABLE",
		4: "WHITELIST",
		5: "BLACKLIST",
		6: "DELETED",
	}
	UserStatusEnum_UserStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"INITIAL":     1,
		"ENABLE":      2,
		"DISABLE":     3,
		"WHITELIST":   4,
		"BLACKLIST":   5,
		"DELETED":     6,
	}
)

func (x UserStatusEnum_UserStatus) Enum() *UserStatusEnum_UserStatus {
	p := new(UserStatusEnum_UserStatus)
	*p = x
	return p
}

func (x UserStatusEnum_UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatusEnum_UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auth_v1_auth_v1_proto_enumTypes[0].Descriptor()
}

func (UserStatusEnum_UserStatus) Type() protoreflect.EnumType {
	return &file_api_auth_v1_auth_v1_proto_enumTypes[0]
}

func (x UserStatusEnum_UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatusEnum_UserStatus.Descriptor instead.
func (UserStatusEnum_UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_v1_proto_rawDescGZIP(), []int{1, 0}
}

type PlatformEnum_Platform int32

const (
	// UNKNOWN 未知
	PlatformEnum_UNKNOWN PlatformEnum_Platform = 0
	// COMPUTER 电脑端
	PlatformEnum_COMPUTER PlatformEnum_Platform = 1
	// MOBILE 移动端
	PlatformEnum_MOBILE PlatformEnum_Platform = 2
	// ANDROID 安卓系统
	PlatformEnum_ANDROID PlatformEnum_Platform = 100
	// IOS 苹果系统
	PlatformEnum_IOS PlatformEnum_Platform = 101
	// WEB 网页
	PlatformEnum_WEB PlatformEnum_Platform = 200
	// H5 网页
	PlatformEnum_H5 PlatformEnum_Platform = 201
	// APPLET 小程序
	PlatformEnum_APPLET PlatformEnum_Platform = 203
	// APP 应用
	PlatformEnum_APP PlatformEnum_Platform = 204
	// ANDROID_APP 安卓应用
	PlatformEnum_ANDROID_APP PlatformEnum_Platform = 205
	// IOS_APP 苹果应用
	PlatformEnum_IOS_APP PlatformEnum_Platform = 206
	// IPAD_APP 平板应用
	PlatformEnum_IPAD_APP PlatformEnum_Platform = 207
)

// Enum value maps for PlatformEnum_Platform.
var (
	PlatformEnum_Platform_name = map[int32]string{
		0:   "UNKNOWN",
		1:   "COMPUTER",
		2:   "MOBILE",
		100: "ANDROID",
		101: "IOS",
		200: "WEB",
		201: "H5",
		203: "APPLET",
		204: "APP",
		205: "ANDROID_APP",
		206: "IOS_APP",
		207: "IPAD_APP",
	}
	PlatformEnum_Platform_value = map[string]int32{
		"UNKNOWN":     0,
		"COMPUTER":    1,
		"MOBILE":      2,
		"ANDROID":     100,
		"IOS":         101,
		"WEB":         200,
		"H5":          201,
		"APPLET":      203,
		"APP":         204,
		"ANDROID_APP": 205,
		"IOS_APP":     206,
		"IPAD_APP":    207,
	}
)

func (x PlatformEnum_Platform) Enum() *PlatformEnum_Platform {
	p := new(PlatformEnum_Platform)
	*p = x
	return p
}

func (x PlatformEnum_Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformEnum_Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auth_v1_auth_v1_proto_enumTypes[1].Descriptor()
}

func (PlatformEnum_Platform) Type() protoreflect.EnumType {
	return &file_api_auth_v1_auth_v1_proto_enumTypes[1]
}

func (x PlatformEnum_Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlatformEnum_Platform.Descriptor instead.
func (PlatformEnum_Platform) EnumDescriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_v1_proto_rawDescGZIP(), []int{2, 0}
}

// LimitType 登录限制类型
type LimitTypeEnum_LimitType int32

const (
	// UNKNOWN 未知
	LimitTypeEnum_UNKNOWN LimitTypeEnum_LimitType = 0
	// UNLIMITED 无限制
	LimitTypeEnum_UNLIMITED LimitTypeEnum_LimitType = 1
	// ONLY_ONE 同一账户仅允许登录一次(验证码...可强制登录)
	LimitTypeEnum_ONLY_ONE LimitTypeEnum_LimitType = 2
	// SAME_PLATFORM 同一账户每个平台都可登录一次(验证码...可强制登录)
	LimitTypeEnum_SAME_PLATFORM LimitTypeEnum_LimitType = 3
)

// Enum value maps for LimitTypeEnum_LimitType.
var (
	LimitTypeEnum_LimitType_name = map[int32]string{
		0: "UNKNOWN",
		1: "UNLIMITED",
		2: "ONLY_ONE",
		3: "SAME_PLATFORM",
	}
	LimitTypeEnum_LimitType_value = map[string]int32{
		"UNKNOWN":       0,
		"UNLIMITED":     1,
		"ONLY_ONE":      2,
		"SAME_PLATFORM": 3,
	}
)

func (x LimitTypeEnum_LimitType) Enum() *LimitTypeEnum_LimitType {
	p := new(LimitTypeEnum_LimitType)
	*p = x
	return p
}

func (x LimitTypeEnum_LimitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LimitTypeEnum_LimitType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auth_v1_auth_v1_proto_enumTypes[2].Descriptor()
}

func (LimitTypeEnum_LimitType) Type() protoreflect.EnumType {
	return &file_api_auth_v1_auth_v1_proto_enumTypes[2]
}

func (x LimitTypeEnum_LimitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LimitTypeEnum_LimitType.Descriptor instead.
func (LimitTypeEnum_LimitType) EnumDescriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_v1_proto_rawDescGZIP(), []int{3, 0}
}

// Payload 授权信息
type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id 唯一id
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// uuid 唯一id
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// key 数据key、缓存key、...
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// platform 平台信息
	Platform PlatformEnum_Platform `protobuf:"varint,4,opt,name=platform,proto3,enum=kit.api.auth.authv1.PlatformEnum_Platform" json:"platform,omitempty"`
	// limit 登录限制类型
	Limit LimitTypeEnum_LimitType `protobuf:"varint,5,opt,name=limit,proto3,enum=kit.api.auth.authv1.LimitTypeEnum_LimitType" json:"limit,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_auth_v1_auth_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payload) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Payload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Payload) GetPlatform() PlatformEnum_Platform {
	if x != nil {
		return x.Platform
	}
	return PlatformEnum_UNKNOWN
}

func (x *Payload) GetLimit() LimitTypeEnum_LimitType {
	if x != nil {
		return x.Limit
	}
	return LimitTypeEnum_UNKNOWN
}

// UserStatusEnum 用户状态
type UserStatusEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserStatusEnum) Reset() {
	*x = UserStatusEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_auth_v1_auth_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStatusEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusEnum) ProtoMessage() {}

func (x *UserStatusEnum) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusEnum.ProtoReflect.Descriptor instead.
func (*UserStatusEnum) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_v1_proto_rawDescGZIP(), []int{1}
}

// Platform 平台标识
type PlatformEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlatformEnum) Reset() {
	*x = PlatformEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_auth_v1_auth_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatformEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformEnum) ProtoMessage() {}

func (x *PlatformEnum) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformEnum.ProtoReflect.Descriptor instead.
func (*PlatformEnum) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_v1_proto_rawDescGZIP(), []int{2}
}

// LimitTypeEnum 登录限制类型
type LimitTypeEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LimitTypeEnum) Reset() {
	*x = LimitTypeEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_auth_v1_auth_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitTypeEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitTypeEnum) ProtoMessage() {}

func (x *LimitTypeEnum) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitTypeEnum.ProtoReflect.Descriptor instead.
func (*LimitTypeEnum) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_v1_proto_rawDescGZIP(), []int{3}
}

var File_api_auth_v1_auth_v1_proto protoreflect.FileDescriptor

var file_api_auth_v1_auth_v1_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6b, 0x69, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x76, 0x31,
	0x22, 0xcb, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x46, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x6b, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x42, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x6b, 0x69, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x80,
	0x01, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75,
	0x6d, 0x22, 0x6e, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x49, 0x53,
	0x41, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x48, 0x49, 0x54, 0x45, 0x4c,
	0x49, 0x53, 0x54, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x4c, 0x49,
	0x53, 0x54, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10,
	0x06, 0x22, 0xb1, 0x01, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x45, 0x6e,
	0x75, 0x6d, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f,
	0x42, 0x49, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49,
	0x44, 0x10, 0x64, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4f, 0x53, 0x10, 0x65, 0x12, 0x08, 0x0a, 0x03,
	0x57, 0x45, 0x42, 0x10, 0xc8, 0x01, 0x12, 0x07, 0x0a, 0x02, 0x48, 0x35, 0x10, 0xc9, 0x01, 0x12,
	0x0b, 0x0a, 0x06, 0x41, 0x50, 0x50, 0x4c, 0x45, 0x54, 0x10, 0xcb, 0x01, 0x12, 0x08, 0x0a, 0x03,
	0x41, 0x50, 0x50, 0x10, 0xcc, 0x01, 0x12, 0x10, 0x0a, 0x0b, 0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49,
	0x44, 0x5f, 0x41, 0x50, 0x50, 0x10, 0xcd, 0x01, 0x12, 0x0c, 0x0a, 0x07, 0x49, 0x4f, 0x53, 0x5f,
	0x41, 0x50, 0x50, 0x10, 0xce, 0x01, 0x12, 0x0d, 0x0a, 0x08, 0x49, 0x50, 0x41, 0x44, 0x5f, 0x41,
	0x50, 0x50, 0x10, 0xcf, 0x01, 0x22, 0x59, 0x0a, 0x0d, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x48, 0x0a, 0x09, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x4f, 0x4e, 0x4c, 0x59, 0x5f, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x41, 0x4d, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x10, 0x03,
	0x42, 0x5d, 0x0a, 0x13, 0x6b, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x76, 0x31, 0x42, 0x10, 0x4b, 0x69, 0x74, 0x41, 0x70, 0x69, 0x41,
	0x75, 0x74, 0x68, 0x41, 0x75, 0x74, 0x68, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6b, 0x61, 0x69, 0x67, 0x75, 0x61, 0x6e,
	0x67, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x72, 0x76, 0x2d, 0x6b, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x75, 0x74, 0x68, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_auth_v1_auth_v1_proto_rawDescOnce sync.Once
	file_api_auth_v1_auth_v1_proto_rawDescData = file_api_auth_v1_auth_v1_proto_rawDesc
)

func file_api_auth_v1_auth_v1_proto_rawDescGZIP() []byte {
	file_api_auth_v1_auth_v1_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_auth_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_auth_v1_auth_v1_proto_rawDescData)
	})
	return file_api_auth_v1_auth_v1_proto_rawDescData
}

var file_api_auth_v1_auth_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_auth_v1_auth_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_auth_v1_auth_v1_proto_goTypes = []interface{}{
	(UserStatusEnum_UserStatus)(0), // 0: kit.api.auth.authv1.UserStatusEnum.UserStatus
	(PlatformEnum_Platform)(0),     // 1: kit.api.auth.authv1.PlatformEnum.Platform
	(LimitTypeEnum_LimitType)(0),   // 2: kit.api.auth.authv1.LimitTypeEnum.LimitType
	(*Payload)(nil),                // 3: kit.api.auth.authv1.Payload
	(*UserStatusEnum)(nil),         // 4: kit.api.auth.authv1.UserStatusEnum
	(*PlatformEnum)(nil),           // 5: kit.api.auth.authv1.PlatformEnum
	(*LimitTypeEnum)(nil),          // 6: kit.api.auth.authv1.LimitTypeEnum
}
var file_api_auth_v1_auth_v1_proto_depIdxs = []int32{
	1, // 0: kit.api.auth.authv1.Payload.platform:type_name -> kit.api.auth.authv1.PlatformEnum.Platform
	2, // 1: kit.api.auth.authv1.Payload.limit:type_name -> kit.api.auth.authv1.LimitTypeEnum.LimitType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_auth_v1_auth_v1_proto_init() }
func file_api_auth_v1_auth_v1_proto_init() {
	if File_api_auth_v1_auth_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_auth_v1_auth_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_auth_v1_auth_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStatusEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_auth_v1_auth_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatformEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_auth_v1_auth_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitTypeEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_auth_v1_auth_v1_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_auth_v1_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_auth_v1_proto_depIdxs,
		EnumInfos:         file_api_auth_v1_auth_v1_proto_enumTypes,
		MessageInfos:      file_api_auth_v1_auth_v1_proto_msgTypes,
	}.Build()
	File_api_auth_v1_auth_v1_proto = out.File
	file_api_auth_v1_auth_v1_proto_rawDesc = nil
	file_api_auth_v1_auth_v1_proto_goTypes = nil
	file_api_auth_v1_auth_v1_proto_depIdxs = nil
}
